version: '3'

services:
  app:
    image: sepitmaan/weather-meather:latest
    container_name: "weather-meather"
    restart: always
    ports:
      - "8080:8080"
    environment:
      OPENWEATHER_APPID: ${OPENWEATHER_APPID}