name: build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk

    - name: Cache Gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Compile and Build
      run: |
        chmod +x gradlew
        ./gradlew --parallel --configure-on-demand clean compileJava compileKotlin assemble

    - name: Run unit tests
      run: ./gradlew --parallel --configure-on-demand test

    - name: Analyze with SonarCloud
      run: ./gradlew --parallel --configure-on-demand sonarqube -Dsonar.projectKey=sepitmaan_weather-meather-server -Dsonar.projectName=weather-meather-server -Dsonar.organization=sepitmaan -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      run: docker build -t sepitmaan/weather-meather .

    - name: Push Docker image
      run: |
        docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker push sepitmaan/weather-meather:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}